[package]
name = "eiji-sub"
version = "0.4.0"
edition = "2021"

[dependencies]
rayon = "1.5"
encoding_rs = "0.8.32"
flate2 = "1.0"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = [ 'runtime-tokio-native-tls', 'sqlite' ] }
