[package]
name = "eiji-sub-ngram"
version = "0.5.0"
edition = "2021"

[dependencies]
rayon = "1.5"
encoding_rs = "0.8.32"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = [ 'runtime-tokio-native-tls', 'sqlite' ] }
log = "0.4.0"
env_logger = "0.10.0"
